# Generated by Django 4.0.3 on 2022-05-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('plays', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
