# Generated by Django 4.0.3 on 2022-05-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moyka', '0002_rename_user_mijoz_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mijoz',
            old_name='name',
            new_name='nomer',
        ),
        migrations.RemoveField(
            model_name='mijoz',
            name='song',
        ),
    ]
