# Generated by Django 4.0.3 on 2022-05-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moyka', '0003_rename_name_mijoz_nomer_remove_mijoz_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mijoz',
            name='plays',
        ),
    ]
