# Generated by Django 4.0.3 on 2022-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moyka', '0004_remove_mijoz_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='nomer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
